services:
  web:
    image: modestin/caregenius:latest 
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    container_name: photomedia-web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env # très importent