# Generated by Django 5.2 on 2025-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('height', models.FloatField(help_text='Taille en mètres')),
                ('weight', models.FloatField(help_text='Poids en kilogrammes')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='M', max_length=10)),
                ('is_pregnant', models.BooleanField(blank=True, help_text='Applicable uniquement si genre = Femme', null=True)),
                ('pathology', models.TextField(blank=True)),
            ],
        ),
    ]
