# Generated by Django 5.2 on 2025-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_user', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('height', models.FloatField(help_text='Taille en mètres')),
                ('weight', models.FloatField(help_text='Poids en kilogrammes')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='M', max_length=10)),
                ('pathology', models.TextField(blank=True)),
            ],
        ),
    ]
